USE CovisionDB;

-- Crear tabla CLIENTE si no existe
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CLIENTE]') AND type = N'U')
BEGIN
    CREATE TABLE CLIENTE (
        ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
        CEDULA NVARCHAR(20) NOT NULL UNIQUE,
        NOMBRE NVARCHAR(100) NOT NULL,
        TELEFONO1 NVARCHAR(15),
        TELEFONO2 NVARCHAR(15),
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE()
    );
END;

-- Crear tabla CARRO si no existe
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CARRO]') AND type = N'U')
BEGIN
    CREATE TABLE CARRO (
        ID_CARRO INT IDENTITY(1,1) PRIMARY KEY,
        PLACA NVARCHAR(10) NOT NULL UNIQUE,
        MARCA NVARCHAR(50) NOT NULL,
        MODELO NVARCHAR(50) NOT NULL,
        COSTO DECIMAL(18, 2) NOT NULL,
        DISPONIBLE BIT NOT NULL DEFAULT 1, -- Booleano
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE()
    );
END;

-- Crear tabla ALQUILER si no existe
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ALQUILER]') AND type = N'U')
BEGIN
    CREATE TABLE ALQUILER (
        ID_ALQUILER INT IDENTITY(1,1) PRIMARY KEY,
        FECHA DATE NOT NULL,
        TIEMPO INT NOT NULL, -- En días
        VALORTOTAL DECIMAL(18, 2) NOT NULL,
        SALDO DECIMAL(18, 2) NOT NULL,
        ABONO_INICIAL DECIMAL(18, 2) NOT NULL,
        DEVUELTO BIT NOT NULL DEFAULT 0, -- Booleano
        ID_CLIENTE INT NOT NULL,
        ID_CARRO INT NOT NULL,
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE()
    );
END;

-- Crear tabla PAGOS si no existe
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PAGOS]') AND type = N'U')
BEGIN
    CREATE TABLE PAGOS (
        ID_PAGO INT IDENTITY(1,1) PRIMARY KEY,
        FECHA DATE NOT NULL,
        VALOR DECIMAL(18, 2) NOT NULL,
        ID_ALQUILER INT NOT NULL,
        CREATED_AT DATETIME2 DEFAULT GETDATE(),
        UPDATED_AT DATETIME2 DEFAULT GETDATE()
    );
END;
